// destinations.js — curated destination data

const destinations = [
  // ── Europe ──────────────────────────────────────────
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    description: 'The City of Light dazzles with world-class art, iconic architecture, and some of the finest food and wine on earth.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80',
    tags: ['romantic', 'art', 'food', 'history'],
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    description: 'An open-air museum where ancient ruins, Renaissance masterpieces, and vibrant street life exist side by side.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80',
    tags: ['history', 'food', 'architecture', 'art'],
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    description: 'Cliffside villages with iconic blue domes, dramatic volcanic caldera views, and breathtaking sunsets.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&q=80',
    tags: ['romantic', 'beaches', 'scenic', 'island'],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    description: 'Gaudí\'s fantastical architecture, a buzzing food scene, and golden beaches all packed into one vibrant city.',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&q=80',
    tags: ['architecture', 'beaches', 'food', 'nightlife'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    description: 'A network of historic canals, world-class museums, and a famously free-spirited culture.',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&q=80',
    tags: ['canals', 'art', 'cycling', 'history'],
  },
  {
    id: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    region: 'Europe',
    description: 'A fairy-tale city of Gothic spires, medieval squares, and a vibrant arts scene — largely untouched by WWII.',
    image: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=600&q=80',
    tags: ['history', 'architecture', 'nightlife', 'scenic'],
  },

  // ── Asia ────────────────────────────────────────────
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    description: 'A city of thrilling contrasts — ancient temples beside neon-lit skyscrapers, serene gardens beside buzzing street markets.',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',
    tags: ['food', 'culture', 'technology', 'nightlife'],
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    description: 'Japan\'s cultural heart, home to thousands of temples, traditional tea houses, and some of the world\'s most beautiful gardens.',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',
    tags: ['culture', 'history', 'nature', 'temples'],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    description: 'A spiritual island of terraced rice paddies, sacred temples, surf beaches, and a deeply artistic local culture.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80',
    tags: ['beaches', 'spiritual', 'nature', 'surfing'],
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    description: 'A sensory overload in the best way — ornate temples, chaotic street markets, rooftop bars, and world-famous street food.',
    image: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=600&q=80',
    tags: ['food', 'temples', 'nightlife', 'culture'],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    description: 'A futuristic garden city where gleaming supertrees, hawker centres, and multicultural neighborhoods coexist.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80',
    tags: ['food', 'architecture', 'modern', 'culture'],
  },

  // ── Americas ────────────────────────────────────────
  {
    id: 'new-york',
    name: 'New York City',
    country: 'USA',
    region: 'Americas',
    description: 'The city that never sleeps — iconic skyline, world-class museums, Broadway shows, and an unmatched energy.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&q=80',
    tags: ['city', 'art', 'food', 'nightlife'],
  },
  {
    id: 'machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    region: 'Americas',
    description: 'The Lost City of the Incas, perched high in the Andes — one of the world\'s most awe-inspiring ancient sites.',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&q=80',
    tags: ['history', 'hiking', 'ancient', 'scenic'],
  },
  {
    id: 'rio',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'Americas',
    description: 'Carnival energy, Christ the Redeemer overlooking the city, lush rainforest, and iconic beaches like Copacabana.',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&q=80',
    tags: ['beaches', 'culture', 'nature', 'scenic'],
  },
  {
    id: 'patagonia',
    name: 'Patagonia',
    country: 'Argentina / Chile',
    region: 'Americas',
    description: 'Wild glaciers, jagged granite peaks, and sweeping steppe at the end of the world — a hiker\'s paradise.',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80',
    tags: ['hiking', 'nature', 'adventure', 'glaciers'],
  },
  {
    id: 'havana',
    name: 'Havana',
    country: 'Cuba',
    region: 'Americas',
    description: 'A city frozen in a beautiful era — crumbling colonial architecture, vintage cars, live salsa, and warm sea air.',
    image: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=600&q=80',
    tags: ['culture', 'history', 'music', 'architecture'],
  },

  // ── Africa ──────────────────────────────────────────
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    description: 'A labyrinth of souks, riads, and spice markets — a feast for the senses wrapped in rose-tinted city walls.',
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=600&q=80',
    tags: ['culture', 'food', 'history', 'markets'],
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    description: 'Table Mountain rising over the ocean, world-class wine country, penguin colonies, and stunning coastal drives.',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&q=80',
    tags: ['nature', 'scenic', 'adventure', 'food'],
  },
  {
    id: 'serengeti',
    name: 'Serengeti',
    country: 'Tanzania',
    region: 'Africa',
    description: 'Witness the Great Migration — millions of wildebeest and zebras crossing vast golden plains under enormous skies.',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80',
    tags: ['wildlife', 'safari', 'nature', 'adventure'],
  },

  // ── Oceania ─────────────────────────────────────────
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    description: 'The Opera House, Harbour Bridge, golden beaches, and a laid-back outdoor culture make Sydney endlessly liveable.',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600&q=80',
    tags: ['beaches', 'city', 'scenic', 'outdoor'],
  },
  {
    id: 'queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    region: 'Oceania',
    description: 'The adventure capital of the world — bungee jumping, ski fields, and stunning fjords backed by the Remarkables.',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600&q=80',
    tags: ['adventure', 'nature', 'skiing', 'scenic'],
  },

  // ── Middle East ─────────────────────────────────────
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'Middle East',
    description: 'A city of superlatives — the world\'s tallest tower, indoor ski slopes, gold souks, and ultra-modern architecture.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80',
    tags: ['modern', 'luxury', 'architecture', 'shopping'],
  },
  {
    id: 'petra',
    name: 'Petra',
    country: 'Jordan',
    region: 'Middle East',
    description: 'The Rose City — a UNESCO World Heritage site where ancient Nabataean temples are carved directly into rose-red cliffs.',
    image: 'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=600&q=80',
    tags: ['history', 'ancient', 'adventure', 'scenic'],
  },
];

export default destinations;
